---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644
  
  - name: Deploy Haproxy
    include_role:
      name: haproxy
    when: inventory_hostname in groups['frontends']
  
  - name: Deploy Tomcat
    include_role:
      name: tomcat
    when: inventory_hostname in groups['apps']
  
  - name: Test Debug
    debug:
      msg: "{{ inventory_hostname_short }}"
    when: inventory_hostname in groups['apps']

  - name: Deploy Apps
    include_role:
      name: app_deploy
    when: inventory_hostname in groups['apps']


#  - name: copy static index.html to tomcat webapps/ansible/index.html
#    template:
#      src: index.html.app1
#      dest: /usr/share/tomcat/webapps/ansible/index.html
#    when: inventory_hostname_short == 'app1'
#
#  - name: copy static index.html to tomcat webapps/ansible/index.html
#    template:
#      src: index.html.app2
#      dest: /usr/share/tomcat/webapps/ansible/index.html
#    when: inventory_hostname_short == 'app2'
  
  - name: Deploy Tomcat
    include_role:
      name: postgresql
    when: inventory_hostname in groups['appdbs']
  
  - name: Deploy Apache 
    include_role:
      name: apache
    when: inventory_hostname in groups['apps']


